dist: xenial
sudo: required
before_install:
  - apt-get install -y libpthread-stubs0-dev  
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Build steps
script:
#  - mkdir build
#  - cd build
  - cmake src && make libImpactSearcher
