# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/sven/Dokumente/Astronomie/Impact Project/ImpactSearcher/src"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/sven/Dokumente/Astronomie/Impact Project/ImpactSearcher"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sven/Dokumente/Astronomie/Impact Project/ImpactSearcher/CMakeFiles" "/home/sven/Dokumente/Astronomie/Impact Project/ImpactSearcher/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/sven/Dokumente/Astronomie/Impact Project/ImpactSearcher/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named image_helper.cpp

# Build rule for target.
image_helper.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 image_helper.cpp
.PHONY : image_helper.cpp

# fast build rule for target.
image_helper.cpp/fast:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/build
.PHONY : image_helper.cpp/fast

image_bmp.o: image_bmp.cpp.o

.PHONY : image_bmp.o

# target to build an object file
image_bmp.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/image_bmp.cpp.o
.PHONY : image_bmp.cpp.o

image_bmp.i: image_bmp.cpp.i

.PHONY : image_bmp.i

# target to preprocess a source file
image_bmp.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/image_bmp.cpp.i
.PHONY : image_bmp.cpp.i

image_bmp.s: image_bmp.cpp.s

.PHONY : image_bmp.s

# target to generate assembly for a file
image_bmp.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/image_bmp.cpp.s
.PHONY : image_bmp.cpp.s

image_png.o: image_png.cpp.o

.PHONY : image_png.o

# target to build an object file
image_png.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/image_png.cpp.o
.PHONY : image_png.cpp.o

image_png.i: image_png.cpp.i

.PHONY : image_png.i

# target to preprocess a source file
image_png.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/image_png.cpp.i
.PHONY : image_png.cpp.i

image_png.s: image_png.cpp.s

.PHONY : image_png.s

# target to generate assembly for a file
image_png.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/image_png.cpp.s
.PHONY : image_png.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/main.cpp.s
.PHONY : main.cpp.s

math_helpers.o: math_helpers.cpp.o

.PHONY : math_helpers.o

# target to build an object file
math_helpers.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/math_helpers.cpp.o
.PHONY : math_helpers.cpp.o

math_helpers.i: math_helpers.cpp.i

.PHONY : math_helpers.i

# target to preprocess a source file
math_helpers.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/math_helpers.cpp.i
.PHONY : math_helpers.cpp.i

math_helpers.s: math_helpers.cpp.s

.PHONY : math_helpers.s

# target to generate assembly for a file
math_helpers.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/math_helpers.cpp.s
.PHONY : math_helpers.cpp.s

thread_1_IO.o: thread_1_IO.cpp.o

.PHONY : thread_1_IO.o

# target to build an object file
thread_1_IO.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_1_IO.cpp.o
.PHONY : thread_1_IO.cpp.o

thread_1_IO.i: thread_1_IO.cpp.i

.PHONY : thread_1_IO.i

# target to preprocess a source file
thread_1_IO.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_1_IO.cpp.i
.PHONY : thread_1_IO.cpp.i

thread_1_IO.s: thread_1_IO.cpp.s

.PHONY : thread_1_IO.s

# target to generate assembly for a file
thread_1_IO.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_1_IO.cpp.s
.PHONY : thread_1_IO.cpp.s

thread_2_center.o: thread_2_center.cpp.o

.PHONY : thread_2_center.o

# target to build an object file
thread_2_center.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_2_center.cpp.o
.PHONY : thread_2_center.cpp.o

thread_2_center.i: thread_2_center.cpp.i

.PHONY : thread_2_center.i

# target to preprocess a source file
thread_2_center.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_2_center.cpp.i
.PHONY : thread_2_center.cpp.i

thread_2_center.s: thread_2_center.cpp.s

.PHONY : thread_2_center.s

# target to generate assembly for a file
thread_2_center.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_2_center.cpp.s
.PHONY : thread_2_center.cpp.s

thread_3_average.o: thread_3_average.cpp.o

.PHONY : thread_3_average.o

# target to build an object file
thread_3_average.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_3_average.cpp.o
.PHONY : thread_3_average.cpp.o

thread_3_average.i: thread_3_average.cpp.i

.PHONY : thread_3_average.i

# target to preprocess a source file
thread_3_average.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_3_average.cpp.i
.PHONY : thread_3_average.cpp.i

thread_3_average.s: thread_3_average.cpp.s

.PHONY : thread_3_average.s

# target to generate assembly for a file
thread_3_average.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_3_average.cpp.s
.PHONY : thread_3_average.cpp.s

thread_4_presort.o: thread_4_presort.cpp.o

.PHONY : thread_4_presort.o

# target to build an object file
thread_4_presort.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_4_presort.cpp.o
.PHONY : thread_4_presort.cpp.o

thread_4_presort.i: thread_4_presort.cpp.i

.PHONY : thread_4_presort.i

# target to preprocess a source file
thread_4_presort.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_4_presort.cpp.i
.PHONY : thread_4_presort.cpp.i

thread_4_presort.s: thread_4_presort.cpp.s

.PHONY : thread_4_presort.s

# target to generate assembly for a file
thread_4_presort.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_4_presort.cpp.s
.PHONY : thread_4_presort.cpp.s

thread_5_check.o: thread_5_check.cpp.o

.PHONY : thread_5_check.o

# target to build an object file
thread_5_check.cpp.o:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_5_check.cpp.o
.PHONY : thread_5_check.cpp.o

thread_5_check.i: thread_5_check.cpp.i

.PHONY : thread_5_check.i

# target to preprocess a source file
thread_5_check.cpp.i:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_5_check.cpp.i
.PHONY : thread_5_check.cpp.i

thread_5_check.s: thread_5_check.cpp.s

.PHONY : thread_5_check.s

# target to generate assembly for a file
thread_5_check.cpp.s:
	$(MAKE) -f CMakeFiles/image_helper.cpp.dir/build.make CMakeFiles/image_helper.cpp.dir/thread_5_check.cpp.s
.PHONY : thread_5_check.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... image_helper.cpp"
	@echo "... image_bmp.o"
	@echo "... image_bmp.i"
	@echo "... image_bmp.s"
	@echo "... image_png.o"
	@echo "... image_png.i"
	@echo "... image_png.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... math_helpers.o"
	@echo "... math_helpers.i"
	@echo "... math_helpers.s"
	@echo "... thread_1_IO.o"
	@echo "... thread_1_IO.i"
	@echo "... thread_1_IO.s"
	@echo "... thread_2_center.o"
	@echo "... thread_2_center.i"
	@echo "... thread_2_center.s"
	@echo "... thread_3_average.o"
	@echo "... thread_3_average.i"
	@echo "... thread_3_average.s"
	@echo "... thread_4_presort.o"
	@echo "... thread_4_presort.i"
	@echo "... thread_4_presort.s"
	@echo "... thread_5_check.o"
	@echo "... thread_5_check.i"
	@echo "... thread_5_check.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

